title: dmerej's blog
author: Dimitri Merejkowsky
languageCode: en-us
canonifyurls: true

theme: minimo

pygmentsStyle: native
pygmentsCodeFences: true

buildDrafts: true

params:
  info:
    description: Personal blog of Dimitri Merejkowsky
  assets:
    customJS: [js/custom.js]
  social: ~
  settings:
    showReadingTime: true

taxonomies:
  tag: tags

menu:
  main:
    - name: Subcribe
      identifier: subscribe
      url: /index.xml
