DefaultContentLanguage: en

title: "dmerej's blog"
author: Dimitri Merejkowsky
languageCode: en-us
canonifyurls: true
baseUrl: https://dmerej.info/blog

theme: minimo

pygmentsStyle: native
pygmentsCodeFences: true

buildDrafts: true

languages:
    en:
      footnoteReturnLinkContents: "<sup>[return]</sup>"
      contentDir: content/en/
      params:
        info:
          description: Personal blog of Dimitri Merejkowsky
        settings:
          dateFormat: 2006, Jan 02
          showReadingTime: true
          blackfriday:
            footnoteReturnLinkContents: return
      menu:
        main:
          - name: RSS
            identifier: subscribe
            url: /index.xml
            weight: 0
    fr:
      contentDir: content/fr/
      footnoteReturnLinkContents: "<sup>[retour]</sup>"
      params:
        info:
          description: Blog personnel de Dimitri Merejkowsky
        settings:
          dateFormat: 02/01 2006
          showReadingTime: true
      menu:
        main:
          - name: "Flux RSS"
            identifier: subscribe
            url: /fr/index.xml
            weight: 0

taxonomies:
  tag: tags

menu:
  main:
    - name: Subscribe
      identifier: subscribe
      url: /index.xml
      weight: 0
