title = "dmerej blog"
author = "Dimitri Merejkowsky"
# Do not hit production while developping
baseurl = "http://dmerej.info/blog/"
languageCode = "en-us"
canonifyurls = true

theme = "blackburn"

pygmentsStyle = "colorful"
pygmentsCodeFences = true

buildDrafts = true

[menu]

[[menu.main]]
name = "Home"
weight = 0
identifier = "home"
url = "/"

[[menu.main]]
name = "About"
weight = 1
identifier = "About"
url = "/pages/about/index.html"

[[menu.main]]
name = "Posts"
weight = 2
identifier = "post"
url = "/post/"

[[menu.main]]
name = "Links"
weight = 3
identifier = "links"
url = "/pages/links/index.html"


[[menu.main]]
name = "Feedback"
weight = 4
identifier = "feedback"
url = "/pages/feedback/index.html"


[[menu.main]]
name = "Subscribe"
weight = 5
identifier = "rss"
url = "/index.xml"


[social]
twitter = "d_merej"
github = "dmerejkowsky"
