title: dmerej's blog
author: Dimitri Merejkowsky
languageCode: en-us
canonifyurls: true
cacheDir: cache

theme: minimo

pygmentsStyle: native
pygmentsCodeFences: true

buildDrafts: true

params:
  info:
    description: Personal blog of Dimitri Merejkowsky
  assets:
    customJS: [js/custom.js]
  social:
    twitter: d_merej
    github: dmerejkowsky
    linkedin: dimitri-merejkowsky-28a3302b
    stackoverflow: 6010239/dimitri-merejkowsky
    config:
      platforms: [twitter, github, linkedin]
  settings:
    showReadingTime: true

taxonomies:
  tag: tags

menu:
  main:
    - name: Subcribe
      identifier: subscribe
      url: /index.xml
