title = "dmerej blog"
author = "Dimitri Merejkowsky"
languageCode = "en-us"
canonifyurls = true
cacheDir = "cache"

theme = "blackburn"

pygmentsStyle = "colorful"
pygmentsCodeFences = true

buildDrafts = false

[params]
description="Dimitri Merejkowsky's blog"

[taxonomies]
tag = "tags"

[menu]

[[menu.main]]
name = "Home"
pre = "<i class='fa fa-home fa-fw'></i>"
weight = 1
identifier = "home"
url = "/"

[[menu.main]]
name = "About"
pre = "<i class='fa fa-user fa-fw'></i>"
weight = 2
identifier = "About"
url = "/pages/about/"

[[menu.main]]
name = "Archives"
pre = "<i class='fa fa-list fa-fw'></i>"
weight = 3
identifier = "archives"
url = "/post/"

[[menu.main]]
name = "Links"
pre = "<i class='fa fa-link fa-fw'></i>"
weight = 4
identifier = "links"
url = "/pages/links/"

[[menu.main]]
name = "Feedback"
pre = "<i class='fa fa-commenting fa-fw'></i>"
weight = 5
identifier = "feedback"
url = "/pages/feedback/"

[[menu.main]]
name = "Subscribe"
pre = "<i class='fa fa-rss fa-fw'></i>"
weight = 6
identifier = "rss"
url = "/index.xml"


[social]
twitter = "d_merej"
github = "dmerejkowsky"
linkedin = "dimitri-merejkowsky-28a3302b"
stackoverflow = "6010239/dimitri-merejkowsky"
