[package]
authors = ["Dimitri Merejkowsky <dimitri.merejkowsky@tanker.io>"]
edition = "2018"
name = "dm-tools"
version = "0.1.0"

[dependencies]
app_dirs = "1.2.1"
structopt = "*"
clipboard = "0.5.0"
anyhow = "1.0.31"
rusqlite = "0.23.1"

[dev-dependencies]
tempdir = "0.3.7"
